dev:
  # mysql配置
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: my_bi
    host: localhost
    port: 3306
    username: root
    password: 123456
  # redis配置
  redis:
    database: 3
    host: localhost
    port: 6379
    timeout: 5000
  # 鱼聪明AI配置
  yuapi:
    client:
      access-key: eysmnfskj8e3gl9558mc3si5om2ua84m
      secret-key: vbwqh5eu7zancoywjf4oovyqk8di39so