# 公共配置文件
# 
# 
spring:
  application:
    name: dvbn-bi
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: ${dev.mysql.driver-class-name}
    url: jdbc:mysql://${dev.mysql.host}:${dev.mysql.port}/${dev.mysql.database}
    username: ${dev.mysql.username}
    password: ${dev.mysql.password}
  # Redis 配置
  redis:
    database: ${dev.redis.database}
    host: ${dev.redis.host}
    port: ${dev.redis.port}
    timeout: ${dev.redis.timeout}
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # RabbitMQ配置
  rabbitmq:
    host: ${dev.rabbitmq.host}
    port: ${dev.rabbitmq.port}
    username: ${dev.rabbitmq.username}
    password: ${dev.rabbitmq.password}
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

# 鱼聪明AI配置
yuapi:
  client:
    access-key: ${dev.yuapi.client.access-key}
    secret-key: ${dev.yuapi.client.secret-key}